# Generated by Django 4.0.5 on 2022-06-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='oryxapi', max_length=225)),
                ('json_auth', models.CharField(max_length=10000)),
                ('dn_auth', models.CharField(max_length=10000)),
                ('json_url', models.CharField(default='https://mpharmatestapp.oryxhr.com/api/Delivery/', max_length=100)),
                ('dn_url', models.CharField(default='https://mpharmatestapp.oryxhr.com/api/Delivery/Report/', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryId', models.CharField(max_length=10, unique=True)),
                ('startDate', models.DateField(verbose_name='date processed')),
                ('shipFromName', models.CharField(max_length=100)),
                ('shipToName', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'DocumentLogs',
                'ordering': ['-startDate'],
            },
        ),
        migrations.CreateModel(
            name='FacilityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=225)),
                ('bu', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['-facility_name'],
            },
        ),
        migrations.CreateModel(
            name='RetailPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10, unique=True)),
                ('product', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'RetailPrices',
                'ordering': ['-price'],
            },
        ),
        migrations.CreateModel(
            name='SalesQuoteLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryId', models.CharField(max_length=10, unique=True)),
                ('created_date', models.DateField(verbose_name='date processed')),
                ('shipFromName', models.CharField(max_length=100)),
                ('shipToName', models.CharField(max_length=100)),
                ('salesquote', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'SalesQuotes',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='WHPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10, unique=True)),
                ('product', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'WHPrices',
                'ordering': ['-price'],
            },
        ),
    ]
