# Generated by Django 4.0.5 on 2022-06-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryId', models.CharField(max_length=20)),
                ('shipToName', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=225)),
                ('qty', models.IntegerField()),
                ('created_date', models.DateField(verbose_name='date processed')),
            ],
        ),
    ]
