# Generated by Django 4.0.5 on 2022-06-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgh', '0002_supplydata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retailprice',
            options={'ordering': ['-price'], 'verbose_name_plural': 'Retail Prices'},
        ),
        migrations.AlterModelOptions(
            name='salesquotelogs',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Sales Quotes'},
        ),
        migrations.AlterModelOptions(
            name='supplydata',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Supply Data'},
        ),
        migrations.AlterModelOptions(
            name='whprice',
            options={'ordering': ['-price'], 'verbose_name_plural': 'WH Prices'},
        ),
    ]
