# Generated by Django 4.0.5 on 2022-06-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgh', '0002_supplydata_alter_retailprice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailprice',
            name='product',
            field=models.CharField(max_length=225),
        ),
    ]
