# Generated by Django 4.0.5 on 2022-06-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgh', '0003_alter_retailprice_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whprice',
            name='product',
            field=models.CharField(max_length=225),
        ),
    ]
