# Generated by Django 4.0.5 on 2022-06-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgh', '0004_alter_whprice_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesquotelogs',
            name='salesquote',
            field=models.FileField(upload_to='assets/Sales Quotes'),
        ),
    ]
